# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "0bc1b8f7-27c5-493f-8cb6-ec7508304561"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: Francis Bato’s Projects
    api_token: "aa2806e408f876f92c02ed7521210b3567436363",
    build_secret: "11eae3a2808c31f544beb61e1884b2cea66dea9614c7712b9b1d0193926c43fc"
  )

  slack(
       message: “Shit got updated. Check your phones.“,
       success: true,
       slack_url: "https://hooks.slack.com/services/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",
       attachment_properties: {
           fields: [
               {
                   title: "Build number",
                   value: ENV["BUILD_NUMBER"],
               }
           ]
       }
   )
end
