# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FitTime' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitTime
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RealmSwift'
  pod 'SnapKit', '~> 4.0.0'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
  pod 'Hue'
  #pod 'Colours/Swift'

  pod 'Fabric'
  pod 'Crashlytics'
end
